---
title: "Introduction to Programming with R"
subtitle: "Control Flow and Functions"
author: "Selene R. Schmittling"
date: "2025-08-01" 
output: 
  pdf_document:
  html_document: 
    number_sections: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Conditional Statements and Flow Control

### If Statement (Conditional)

```{r if-statement}

# Use relational operator
numWolves = 12 # number per week
if (numWolves <= 5) {
  isWolfPack = FALSE
}
isWolfPack

# Use a logical operator
talleyWolf = TRUE
eatsMeat = TRUE
if (talleyWolf==TRUE && eatsMeat==FALSE) {
  # I'm a vegetarian
  goTuffys = TRUE
}
goTuffys # This may fail if eatsBurger wasn't defined above!

# Use logical variable
wolf.calorie.count <- 0

if (eatsMeat) {
  wolf.calorie.count <- wolf.calorie.count + 650
}
wolf.calorie.count
```

```{r if-else-statement}

# increase calorie count
eatsMeat <- TRUE
wolf.calorie.count <- 0
numBurgersEaten  <-  0 # number per week

if (eatsMeat) {
  my.calorie.count <- wolf.calorie.count + 650
  numBurgersEaten <- numBurgersEaten + 1
} else {
  wolf.calorie.count <- wolf.calorie.count + 60 # I should choose this more often
}
numBurgersEaten
wolf.calorie.count

# make sure you have open ({) and closed (}) braces! 
# Let's remove one and see what R does. 
# Also note, if you put your cursor after a brace (or a bracket for that matter) it will # highlight the matching brace or bracket

```

```{r else-if-statements}
numBurgersEaten  <-  2 # number per week

if (numBurgersEaten <= 1) {
  print("Not bad.")
} else if ((numBurgersEaten > 1) && (numBurgersEaten <= 3)) {
  print("Dont eat any burgers for a few weeks")
  # Can put many more lines of code.
} else {
  print("Warning, warning!! Too many burgers!")
}
```

### For Loop

```{r for-loops}

# Simplest example
for (i in 1:5) {
  print(i) # spice it up and divide i by 2
}

vector1 = c("one", "two", "three", "four", "five")
# Can iterate over items in a vector
for (x in vector1) {
  print(x)
}

vector2 = c(2, 4, 6, 8, 10)
for (y in vector2) {
  print(y**y)
}
```

```{r nested-for}
# Make a matrix
data = rnorm(60, 64, 6)
wtWolves = matrix(data, nrow=10, ncol=6, byrow = TRUE)
print(wtWolves)

# Lets print every value in the matrix out one at a time
# REMEMBER TO MAKE SURE YOU HAVE OPEN & CLOSED BRACES!
for (row in 1:10) {
  for (col in 1:6) {
    print(wtWolves[row,col])
  }
}

# We can use functions to extract number of rows and cols from the data structure
for (row in 1:nrow(wtWolves)) {
  for (col in 1:ncol(wtWolves)) {
    print(wtWolves[row,col])
  }
}

# How would you use this same kind of structure to access data in a 3-D array?
wtWolves3D = array(wtWolves, dim=c(10,3,2))
wtWolves3D
for (row in 1:10) {
  for (col in 1:3) {
    for (dim in 1:2) {
      print(wtWolves3D[row, col, dim])
    }
  }
}

```

### While Loops

```{r while-loop}
# monitor our loop using this logical variable
moreWolves = TRUE
numWolves <- 10

while (moreWolves == TRUE) {
  # a wolf leaves
  numWolves = numWolves - 1
  if (numWolves == 0) {
    moreWolves = FALSE
  }
  print(paste('Number of wolves: ', numWolves))
}



# Broken While loop
# Uncomment and run, but comment it back before rendering notebook!
# monitor our loop using this logical variable
# moreWolves = TRUE
# numWolves <- 10
# 
# while (moreWolves == TRUE) {
#   # a wolf leaves
#   numWolves = numWolves - 1
#   Sys.sleep(.25) # Slows code down enough to keep it from crashing
#   print(paste('Number of wolves: ', numWolves))
# }


```

```{r more-efficient-while}

# Initial version of while loop with print statements
# removed

moreWolves = TRUE
numWolves <- 10

while (moreWolves == TRUE) {
  # a wolf leaves
  numWolves = numWolves - 1
  if (numWolves == 0) {
    moreWolves = FALSE
  }
  print(paste('Number of wolves: ', numWolves))
}


# Walk through the steps in your head. Is there anything that seems duplicative? Focus on the "if" statement used above to change the value of "eatsHamburger".

# What if we just use numBurgersEaten as our "while" test?
# How you you rewrite it to use that instead?

moreWolves = TRUE
numWolves <- 10

while (numWolves > 0) {
  # a wolf leaves
  numWolves = numWolves - 1
  print(paste('Number of wolves: ', numWolves))
}

```

```{r breaking-out}
# Use a for loop as an example, but this will work with if and while statements too

for (i in 1:10) {
  print(paste("Current value:", i))
  
  # if value = 7 print a different message and exit loop
  if (i == 7) {
    print("Elvis has left the building. Bye!")
    break # this statement will end the loop change 7 to another number
  }
}

```

## Functions

### Built-In

```{r built-in-function-call}
# define some data
data <- data.frame(weight = c(50,50.000001,45,135,85), 
                   name = c("Artemis", "Aurora", "Fang", "Fen", "Snoopy"))

# generate plot
barplot(data$weight, 
        names.arg = data$name, 
        col="red", 
        ylab="Weight of Wolf (lbs)")

```

```{r function-flavors-and-return-values}
# using barplot() S3 Method for class `formula`
# define some data
data <- data.frame(weight = c(50,50.000001,45,135,85), 
                   name = c("Artemis", "Aurora", "Fang", "Fen", "Snoopy"))

# generate plot
barplot(weight ~ name, 
        data = data, 
        col="red", 
        ylab="Weight of Wolf (lbs)")

# does a plot have a return value? Yes!
bp <- barplot(weight ~ name, 
        data = data, 
        col="red", 
        ylab="# of Regional Managers")
bp
```

### Practice Using Built-In Functions

```{r built-in-practice}
# Make some data to plot. Uses rnorm() to generate 50 values drawn from a normal distribution with a mean of 0 and standard deviation of 4.25
data <- rnorm(50, mean=0, sd=4.25)

# You can use the function built in function hist() to create a histogram of data
# Use ?hist() in the Console to learn how to call the function

# What are the required parameters? Call the function using only the required parameter
hist(data)

# add a breaks statement to increase the number of bars (bins)
# hint: count the bars in the last plot and increase it
hist(data, breaks=15)

# set the freq argument to TRUE and then FALSE and look at the difference
hist(data, breaks=15, freq=TRUE)
hist(data, breaks=15, freq=FALSE)
```

### Packages

```{r load-a-package}
library(openxlsx2)

# load NCSU Mascot data using openxlsx2
# Because we are in a notebook it sees the current working directory as "notebooks"
# To use a relative file name, we use "../" to "go" up a level and then "/data/" 
# points to documents in the data directory. Once that is entered if we hit Tab we will get a list of files to choose from.

# Load data using read_xlsx() function
# Note: 
mascot.data <- read_xlsx("data/NCSU_Mascots_v1.xlsx")
# print the first 6 rows of the data using the head() function
print(head(mascot.data))
```

```{r write-to-excel}
# Let's write out the first 20 rows of the mascot data to an .xlsx file. Save the file in the output folder
write_xlsx(mascot.data[1:20, ], "output/mascot_20.xlsx")

# Open the data and compare it to "../data/NCSU_Mascots_v1.xlsx"

```

### User-defined Functions

```{r write-a-mean-function}
# Function: avg(x, N)
# Required parameters:
#   * x: a vector of numbers
#   * N: the number of elements in the vector
# Return value: avg returns the mean of the numbers in the vector.

avg <- function(x, N){
  sumX <-  0
  for (i in 1:N) {
    sumX <- sumX + x[i]
  }
  avgX <- sumX/N
  return(avgX)
}
# Once we run this code we should see `avg` listed under "Functions" in the Environment tab of the Environment pane.

# Let's Test our Function
# Define some vectors
vector.1 <- runif(50, min=0, max=100) # pulls 50 values from a uniform distribution
vector.2 <- rnorm(50, 0, 1) # pulls 50 numbers from a normal distributions

print(avg(vector.1, 50))
print(mean(vector.1))
print(avg(vector.2, 50))
print(mean(vector.2))

```

### Practice Writing Your Own Function

```{r write-sd-function}
# Make sure we've run the code defining our "avg" function
# Hint: look in the Environment Tab of the Environment Pane!
standev <- function(x, N){
  # calculate mean
  my.avg <- avg(x, N)
  # initialize our running sum
  my.sum <- 0
  for (num in x) {
    # subtract mean from our number and square it
    my.value <- (num-my.avg)**2
    # add this value to our running sum
    my.sum <- my.sum + my.value
  }
  my.variance <- my.sum / (N-1)
  my.standev <- sqrt(my.variance)
  return(my.standev)
}

# test your function
# Define some vectors
vector.1 <- runif(50, min=0, max=100) # pulls 50 values from a uniform distribution
vector.2 <- rnorm(50, 0, 1) # pulls 50 numbers from a normal distributions

# compare output from your function to the R function `sd()`
print(standev(vector.1, 50))
print(sd(vector.1))
print(standev(vector.2, 50))
print(sd(vector.2))

```
